# Generated by Django 5.0 on 2026-01-01 16:47

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ville_depart', models.CharField(max_length=100, verbose_name='Ville de départ')),
                ('ville_arrivee', models.CharField(max_length=100, verbose_name="Ville d'arrivée")),
                ('date_depart', models.DateField(verbose_name='Date de départ')),
                ('heure_depart', models.TimeField(verbose_name='Heure de départ')),
                ('duree_estimee', models.IntegerField(help_text='Durée en minutes', verbose_name='Durée estimée')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base')),
                ('capacite_max', models.IntegerField(verbose_name='Capacité maximale')),
                ('places_reservees', models.IntegerField(default=0, verbose_name='Places réservées')),
                ('type_trajet', models.CharField(choices=[('ordinaire', 'Ordinaire'), ('vip', 'VIP')], default='ordinaire', max_length=20, verbose_name='Type de trajet')),
                ('is_vip', models.BooleanField(default=False, verbose_name='Trajet VIP')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='planifie', max_length=20, verbose_name='Statut')),
                ('compagnie_nom', models.CharField(blank=True, max_length=100, verbose_name='Nom de la compagnie')),
                ('bus_immatriculation', models.CharField(blank=True, max_length=50, verbose_name='Immatriculation du bus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
                'db_table': 'trips_trajet',
                'ordering': ['-date_depart', '-heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trajet_id', models.UUIDField(verbose_name='ID du trajet')),
                ('client_telephone', models.CharField(max_length=20, verbose_name='Téléphone du client')),
                ('client_nom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('client_prenom', models.CharField(max_length=100, verbose_name='Prénom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('numero_ticket', models.CharField(max_length=50, unique=True, verbose_name='Numéro de ticket')),
                ('numero_siege', models.IntegerField(verbose_name='Numéro de siège')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('payee', 'Payée'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé')),
                ('date_reservation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de réservation')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'trips_reservation',
                'ordering': ['-date_reservation'],
                'unique_together': {('trajet_id', 'numero_siege')},
            },
        ),
    ]
