# Generated by Django 5.0 on 2026-01-02 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFonds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raison', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_fonds', to='locations.gare')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_fonds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_demandes_fonds',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='MembreGare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('ajout_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('gare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='locations.gare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gares_associees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager_membres_gare',
                'ordering': ['-date_ajout'],
                'unique_together': {('user', 'gare')},
            },
        ),
    ]
