# Generated by Django 5.0 on 2025-12-30 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('code_suivi', models.CharField(max_length=50, unique=True, verbose_name='Code de suivi')),
                ('description', models.TextField(verbose_name='Description du contenu')),
                ('poids', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Poids (kg)')),
                ('valeur_declaree', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valeur déclarée (FCFA)')),
                ('destinataire_nom', models.CharField(max_length=200, verbose_name='Nom du destinataire')),
                ('destinataire_telephone', models.CharField(max_length=20, verbose_name='Téléphone destinataire')),
                ('destinataire_adresse', models.TextField(verbose_name='Adresse destinataire')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de transport'), ('arrive', 'Arrivé à destination'), ('en_livraison', 'En cours de livraison'), ('livre', 'Livré'), ('probleme', 'Problème'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA)')),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('date_expedition', models.DateTimeField(auto_now_add=True, verbose_name="Date d'expédition")),
                ('date_arrivee_prevue', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée prévue")),
                ('date_arrivee_reelle', models.DateTimeField(blank=True, null=True, verbose_name="Date d'arrivée réelle")),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='Date de livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_expedies', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
                ('gare_arrivee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_arrivees', to='locations.gare', verbose_name="Gare d'arrivée")),
                ('gare_depart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colis_departs', to='locations.gare', verbose_name='Gare de départ')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
                'ordering': ['-date_expedition'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEtat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ancien_statut', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de transport'), ('arrive', 'Arrivé à destination'), ('en_livraison', 'En cours de livraison'), ('livre', 'Livré'), ('probleme', 'Problème'), ('annule', 'Annulé')], max_length=20, null=True, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours de transport'), ('arrive', 'Arrivé à destination'), ('en_livraison', 'En cours de livraison'), ('livre', 'Livré'), ('probleme', 'Problème'), ('annule', 'Annulé')], max_length=20, verbose_name='Nouveau statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='parcels.colis', verbose_name='Colis')),
                ('localisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.gare', verbose_name='Localisation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Historique d'état",
                'verbose_name_plural': "Historiques d'état",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('assignee', 'Assignée'), ('en_cours', 'En cours'), ('livree', 'Livrée'), ('echec', 'Échec')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_assignation', models.DateTimeField(blank=True, null=True, verbose_name="Date d'assignation")),
                ('date_debut', models.DateTimeField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('signature_destinataire', models.TextField(blank=True, verbose_name='Signature destinataire (base64)')),
                ('photo_livraison', models.URLField(blank=True, verbose_name='Photo de livraison')),
                ('commentaire_livreur', models.TextField(blank=True, verbose_name='Commentaire du livreur')),
                ('raison_echec', models.TextField(blank=True, verbose_name="Raison de l'échec")),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='parcels.colis', verbose_name='Colis')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livraisons', to=settings.AUTH_USER_MODEL, verbose_name='Livreur')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-created_at'],
            },
        ),
    ]
